# Generated by Django 2.1.7 on 2019-06-27 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ope_director',
            fields=[
                ('type', models.CharField(max_length=500)),
                ('sys_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('ope_director', models.CharField(max_length=500)),
                ('second_director', models.CharField(blank=True, max_length=500, null=True)),
                ('third_director', models.CharField(blank=True, max_length=500, null=True)),
                ('changshang', models.CharField(blank=True, max_length=500, null=True)),
                ('contacts', models.CharField(blank=True, max_length=100, null=True)),
                ('tel_phone', models.CharField(blank=True, max_length=500, null=True)),
                ('backup_path', models.CharField(blank=True, max_length=500, null=True)),
                ('remark', models.TextField(blank=True, default='', null=True)),
            ],
            options={
                'db_table': 'ope_director',
            },
        ),
        migrations.CreateModel(
            name='ser_version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sys_name', models.CharField(max_length=500)),
                ('ope_director', models.CharField(max_length=500)),
                ('mod_name', models.CharField(max_length=500)),
                ('ser_ip', models.CharField(max_length=50)),
                ('process_name', models.CharField(max_length=500)),
                ('version', models.CharField(max_length=100)),
                ('process_path', models.CharField(max_length=500)),
                ('conf_path', models.CharField(max_length=500)),
                ('log_path', models.CharField(max_length=500)),
                ('change_path', models.CharField(max_length=500)),
                ('md5', models.CharField(max_length=100)),
                ('remark', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ser_version',
            },
        ),
        migrations.CreateModel(
            name='ver_repostory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sys_name', models.CharField(max_length=500)),
                ('mod_name', models.CharField(max_length=500)),
                ('process_name', models.CharField(max_length=500)),
                ('version', models.CharField(max_length=100)),
                ('process_path', models.CharField(max_length=500)),
                ('md5', models.CharField(max_length=100)),
                ('remark', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ver_repostory',
            },
        ),
        migrations.AlterUniqueTogether(
            name='ver_repostory',
            unique_together={('sys_name', 'mod_name')},
        ),
        migrations.AlterUniqueTogether(
            name='ser_version',
            unique_together={('sys_name', 'mod_name', 'ser_ip')},
        ),
    ]
