# Generated by Django 2.1.7 on 2019-05-22 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vir_machine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vir_machine',
            name='disk_total',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vir_machine',
            name='vir_cpu',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vir_machine',
            name='vir_memory',
            field=models.IntegerField(),
        ),
    ]
