# Generated by Django 2.1.7 on 2019-05-22 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vir_machine', '0002_auto_20190522_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vir_machine',
            name='disk_type',
            field=models.TextField(null=True),
        ),
    ]
