# Generated by Django 2.1.7 on 2019-06-03 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ser_version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sys_name', models.CharField(max_length=500)),
                ('ope_director', models.CharField(max_length=500)),
                ('mod_name', models.CharField(max_length=500)),
                ('ser_ip', models.CharField(max_length=50)),
                ('process_name', models.CharField(max_length=500)),
                ('version', models.CharField(max_length=100)),
                ('process_path', models.CharField(max_length=500)),
                ('conf_path', models.CharField(max_length=500)),
                ('log_path', models.CharField(max_length=500)),
                ('change_path', models.CharField(max_length=500)),
                ('md5', models.CharField(default='', max_length=100)),
                ('remark', models.TextField(null=True)),
            ],
            options={
                'db_table': 'ser_version',
            },
        ),
        migrations.CreateModel(
            name='ver_repostory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sys_name', models.CharField(max_length=500)),
                ('mod_name', models.CharField(max_length=500)),
                ('process_name', models.CharField(max_length=500)),
                ('version', models.CharField(max_length=100)),
                ('process_path', models.CharField(max_length=500)),
                ('md5', models.CharField(max_length=100)),
                ('remark', models.TextField(null=True)),
            ],
            options={
                'db_table': 'ver_repostory',
            },
        ),
        migrations.AlterUniqueTogether(
            name='ver_repostory',
            unique_together={('sys_name', 'mod_name')},
        ),
        migrations.AlterUniqueTogether(
            name='ser_version',
            unique_together={('sys_name', 'mod_name')},
        ),
    ]
