# Generated by Django 2.1.7 on 2019-06-13 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ope_director',
            fields=[
                ('type', models.CharField(max_length=500)),
                ('sys_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('ope_director', models.CharField(max_length=500)),
                ('second_director', models.CharField(max_length=500)),
                ('third_director', models.CharField(max_length=500)),
                ('changshang', models.CharField(max_length=500, null=True)),
                ('contacts', models.CharField(max_length=100, null=True)),
                ('tel_phone', models.CharField(max_length=500, null=True)),
                ('backup_path', models.CharField(max_length=500, null=True)),
                ('remark', models.TextField(null=True)),
            ],
            options={
                'db_table': 'ope_director',
            },
        ),
    ]
