# Generated by Django 2.1.7 on 2019-06-04 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sys_app', '0002_auto_20190603_1625'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ser_version',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='ver_repostory',
            unique_together=set(),
        ),
    ]
