# Generated by Django 2.1.7 on 2019-06-27 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys_app', '0003_auto_20190613_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ope_director',
            name='backup_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ope_director',
            name='changshang',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ope_director',
            name='contacts',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ope_director',
            name='remark',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='ope_director',
            name='second_director',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ope_director',
            name='tel_phone',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ope_director',
            name='third_director',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ser_version',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ver_repostory',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='ser_version',
            unique_together={('sys_name', 'mod_name', 'ser_ip')},
        ),
    ]
