# Generated by Django 2.1.7 on 2019-06-04 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sys_app', '0003_auto_20190604_1019'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ser_version',
            unique_together={('sys_name', 'mod_name')},
        ),
        migrations.AlterUniqueTogether(
            name='ver_repostory',
            unique_together={('sys_name', 'mod_name')},
        ),
    ]
