# Generated by Django 2.1.7 on 2019-05-20 03:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default name', max_length=50)),
                ('blog_id', models.IntegerField(default=None, null=True)),
                ('user_id', models.IntegerField(default=1, null=True)),
                ('user_name', models.CharField(default='default name', max_length=50)),
                ('content', models.CharField(default='请填写内容', max_length=9999)),
                ('create_at', models.IntegerField(default=1558321795, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='请填写内容')),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('comment_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_user', to=settings.AUTH_USER_MODEL)),
                ('to_blog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_blog_id', to='main.Blog')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
