# Generated by Django 2.1.7 on 2019-05-20 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190520_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_info', models.TextField(default='请填写内容')),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='create_at',
            field=models.IntegerField(default=1558322718, null=True),
        ),
    ]
