# Generated by Django 2.1.7 on 2019-05-20 03:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_auto_20190520_1125'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Discuss',
        ),
        migrations.AlterField(
            model_name='blog',
            name='create_at',
            field=models.IntegerField(default=1558322937, null=True),
        ),
    ]
