# Generated by Django 2.1.7 on 2019-05-20 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190520_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='create_at',
            field=models.IntegerField(default=1558325749, null=True),
        ),
    ]
