# Generated by Django 2.1.7 on 2019-05-20 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190520_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='create_at',
            field=models.IntegerField(default=1558336833, null=True),
        ),
        migrations.AlterField(
            model_name='discuss',
            name='to_user',
            field=models.CharField(default='default name', max_length=50),
        ),
    ]
