# Generated by Django 2.1.7 on 2019-05-20 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190520_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(default='请填写内容'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='create_at',
            field=models.IntegerField(default=1558343181, null=True),
        ),
    ]
