# Generated by Django 2.1.7 on 2019-05-29 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190528_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='create_at',
            field=models.IntegerField(default=1559115417, null=True),
        ),
    ]
